# params.pp
# Set up ClamAV parameters defaults etc.
#
# @Todo: add osx support with ClamXav
#

class clamav::params (
  Boolean $manage_repo,
  String  $clamav_package,
  String  $clamav_version,
  String  $user,
  String  $group,
  Integer $uid,
  Integer $gid,
  Stdlib::Absolutepath $shell,
  Stdlib::Absolutepath $home,
  String $clamd_version,
  Stdlib::Absolutepath $clamd_config,
  String $clamd_service,
  Hash $clamd_options,
  Stdlib::Absolutepath $clamd_default_localsocket,
  Stdlib::Absolutepath $clamd_default_pidfile,
  String $freshclam_default_databaseowner,
  Stdlib::Absolutepath $freshclam_config,
  Hash $freshclam_options,
  Stdlib::Absolutepath $clamd_default_databasedirectory,
  Boolean $clamd_default_logsyslog,
  Stdlib::Absolutepath $clamd_default_temporarydirectory,
  Optional[String] $freshclam_service,
  Optional[String] $freshclam_package,
  Optional[String] $freshclam_version,
  Optional[Stdlib::Absolutepath] $freshclam_sysconfig,
  Optional[String] $freshclam_delay,
  Optional[String] $comment,
  Optional[Array[String]] $groups,
  Optional[String] $clamd_package,
  Optional[Stdlib::Absolutepath] $clamd_default_logfile,
  Optional[Stdlib::Absolutepath] $freshclam_default_updatelogfile,
  Optional[Stdlib::Absolutepath] $freshclam_default_pidfile,
  Optional[String] $clamav_milter_package,
  Optional[String] $clamav_milter_version,
  Optional[String] $clamav_milter_config ,
  Optional[String] $clamav_milter_service,
  Optional[Hash] $clamav_milter_options,
  Optional[Hash] $clamav_milter_default_options,
  Optional[Boolean] $clamd_default_logrotate,
){

  #### init vars ####
  $manage_user                  = false
  $manage_clamd                 = false
  $manage_clamav_milter         = false
  $manage_freshclam             = false
  $clamd_service_ensure         = 'running'
  $clamd_service_enable         = true
  $freshclam_service_ensure     = 'running'
  $freshclam_service_enable     = true
  $clamav_milter_service_ensure = 'running'
  $clamav_milter_service_enable = true

  $clamd_common_defaults = {
    'AlgorithmicDetection'           => true,
    'AllowAllMatchScan'              => true,
    'ArchiveBlockEncrypted'          => false,
    'Bytecode'                       => true,
    'BytecodeSecurity'               => 'TrustSigned',
    'BytecodeTimeout'                => '60000',
    'CommandReadTimeout'             => '5',
    'CrossFilesystems'               => true,
    'DatabaseDirectory'              => $clamd_default_databasedirectory,
    'Debug'                          => false,
    'DetectPUA'                      => false,
    'DisableCertCheck'               => false,
    'ExitOnOOM'                      => false,
    'ExtendedDetectionInfo'          => true,
    'FixStaleSocket'                 => true,
    'FollowDirectorySymlinks'        => false,
    'FollowFileSymlinks'             => false,
    'ForceToDisk'                    => false,
    'Foreground'                     => false,
    'HeuristicScanPrecedence'        => false,
    'IdleTimeout'                    => '30',
    'LeaveTemporaryFiles'            => false,
    'LocalSocket'                    => $clamd_default_localsocket,
    'LocalSocketGroup'               => $group,
    'LocalSocketMode'                => '666',
    'LogClean'                       => false,
    'LogFacility'                    => 'LOG_LOCAL6',
    'LogFile'                        => $clamd_default_logfile,
    'LogFileMaxSize'                 => '0',
    'LogFileUnlock'                  => false,
    'LogRotate'                      => $clamd_default_logrotate,
    'LogSyslog'                      => $clamd_default_logsyslog,
    'LogTime'                        => true,
    'LogVerbose'                     => false,
    'MaxConnectionQueueLength'       => '15',
    'MaxDirectoryRecursion'          => '15',
    'MaxEmbeddedPE'                  => '10M',
    'MaxHTMLNoTags'                  => '2M',
    'MaxHTMLNormalize'               => '10M',
    'MaxQueue'                       => '100',
    'MaxScriptNormalize'             => '5M',
    'MaxThreads'                     => '12',
    'MaxZipTypeRcg'                  => '1M',
    'OLE2BlockMacros'                => false,
    'OfficialDatabaseOnly'           => false,
    'PhishingAlwaysBlockCloak'       => false,
    'PhishingAlwaysBlockSSLMismatch' => false,
    'PhishingScanURLs'               => true,
    'PhishingSignatures'             => true,
    'PidFile'                        => $clamd_default_pidfile,
    'ReadTimeout'                    => '180',
    'ScanArchive'                    => true,
    'ScanELF'                        => true,
    'ScanHTML'                       => true,
    'ScanMail'                       => true,
    'ScanOLE2'                       => true,
    'ScanOnAccess'                   => false,
    'ScanPE'                         => true,
    'ScanPartialMessages'            => false,
    'ScanSWF'                        => true,
    'SelfCheck'                      => '3600',
    'SendBufTimeout'                 => '200',
    'StreamMaxLength'                => '25M',
    'StructuredDataDetection'        => false,
    'TemporaryDirectory'             => $clamd_default_temporarydirectory,
    'User'                           => $user,
  }

  $clamd_os_specific_defaults = lookup('clamav::params::clamd_os_specific_default_options', Hash, deep, {})
  #  'DetectBrokenExecutables'        => false,
  $clamd_default_options = merge($clamd_common_defaults, $clamd_os_specific_defaults)

  $freshclam_default_options = {
    'Bytecode'                 => true,
    'Checks'                   => '24',
    'CompressLocalDatabase'    => 'no',
    'ConnectTimeout'           => '30',
    'DNSDatabaseInfo'          => 'current.cvd.clamav.net',
    'DatabaseDirectory'        => $clamd_default_databasedirectory,
    'DatabaseMirror'           => ['db.local.clamav.net', 'database.clamav.net'],
    'DatabaseOwner'            => $freshclam_default_databaseowner,
    'Debug'                    => false,
    'Foreground'               => false,
    'LogFacility'              => 'LOG_LOCAL6',
    'LogFileMaxSize'           => '0',
    'LogRotate'                => $clamd_default_logrotate,
    'LogSyslog'                => $clamd_default_logsyslog,
    'LogTime'                  => true,
    'LogVerbose'               => false,
    'MaxAttempts'              => '5',
    'PidFile'                  => $freshclam_default_pidfile,
    'ReceiveTimeout'           => '30',
    'ScriptedUpdates'          => 'yes',
    'TestDatabases'            => 'yes',
    'UpdateLogFile'            => $freshclam_default_updatelogfile,
  }
}
